name: gpiod
description:
  FFI for libgpiod
version: 2.0.1
repository: https://github.com/DisDis/gpiod

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ffi: ^1.0.0
  meta: ^1.3.0
  async: ^2.5.0

#dev_dependencies:

