name: gpiod
description:
  FFI for libgpiod, easy access to RaspberryPi gpio.
version: 3.0.1
repository: https://github.com/DisDis/gpiod

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  ffi: ^1.2.0
  meta: ^1.3.0
  async: ^2.5.0
