name: gpiod
description:
  FFI for libgpiod
version: 1.0.1
repository: https://github.com/DisDis/gpiod

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  ffi: ^0.1.3
  meta: ^1.1.8
  async: ^2.4.0

#dev_dependencies:

