name: gpiod
description:
  FFI for libgpiod
version: 0.0.1
repository: https://github.com/DisDis/gpiod

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  logging: ^0.11.0
  ffi: 0.1.3

#dev_dependencies:

